openapi: 3.1.0
info:
  title: API сервера проекта «Шесть городов»
  description: |-
    REST API для сервера проекта «Шесть городов».  
    Включает маршруты для работы с пользователями, предложениями и комментариями.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.1.0

tags:
  - name: user
    description: Действия с пользователями.
  - name: offers
    description: Действия с предложениями по аренде.
  - name: comments
    description: Действия с комментариями.

paths:
  /user/register:
    post:
      tags: [users]
      summary: Регистрация пользователя
      operationId: registerUser
      requestBody:
        required: true
        description: Информация для создания нового пользователя.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createUser"
      responses:
        "201":
          description: Пользователь зарегистрирован.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        "400":
          $ref: "#/components/responses/ValidationError"
        "409":
          description: Пользователь с таким email уже существует.
        default:
          $ref: "#/components/responses/InternalError"

  /user/login:
    post:
      tags: [users]
      summary: Авторизация пользователя
      operationId: loginUser
      requestBody:
        required: true
        description: Данные для входа в систему.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginUser"
      responses:
        "200":
          description: Авторизация прошла успешно.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/authToken"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "400":
          $ref: "#/components/responses/ValidationError"

  /user/logout:
    post:
      tags: [users]
      summary: Выход из системы
      operationId: logoutUser
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Успешный выход из системы.
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /user/check:
    get:
      tags: [users]
      summary: Проверка состояния пользователя
      operationId: getAuthorizedUser
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Пользователь авторизован.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /offers:
    get:
      tags: [offers]
      summary: Получить список предложений
      operationId: getOffers
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 60
          description: Количество возвращаемых предложений.
      responses:
        "200":
          description: Список предложений.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/offerListItem"

    post:
      tags: [offers]
      summary: Создать новое предложение
      operationId: createOffer
      security:
        - bearerAuth: []
      requestBody:
        required: true
        description: Информация для создания нового предложения.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createOffer"
      responses:
        "201":
          description: Предложение создано.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/offer"
        "400":
          $ref: "#/components/responses/ValidationError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /offers/{offerId}:
    get:
      tags: [offers]
      summary: Получить предложение по ID
      operationId: getOfferById
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Детальная информация о предложении.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/offer"
        "404":
          $ref: "#/components/responses/NotFoundError"

    patch:
      tags: [offers]
      summary: Редактировать предложение
      operationId: updateOffer
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/updateOffer"
      responses:
        "200":
          description: Предложение обновлено.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/offer"
        "400":
          $ref: "#/components/responses/ValidationError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          description: Нельзя редактировать чужое предложение.
        "404":
          $ref: "#/components/responses/NotFoundError"

    delete:
      tags: [offers]
      summary: Удалить предложение
      operationId: deleteOffer
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Предложение удалено.
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          description: Нельзя удалять чужое предложение.
        "404":
          $ref: "#/components/responses/NotFoundError"

  /offers/premium/{city}:
    get:
      tags: [offers]
      summary: Получить премиальные предложения для города
      operationId: getPremiumOffers
      parameters:
        - name: city
          in: path
          required: true
          schema:
            type: string
            enum: [Paris, Cologne, Brussels, Amsterdam, Hamburg, Dusseldorf]
      responses:
        "200":
          description: Список премиальных предложений.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/offerListItem"

  /offers/favorites:
    get:
      tags: [offers]
      summary: Получить избранные предложения
      operationId: getFavoriteOffers
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Список избранных предложений.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/offerListItem"
        "401":
          $ref: "#/components/responses/UnauthorizedError"

  /offers/{offerId}/favorite:
    post:
      tags: [offers]
      summary: Добавить предложение в избранное
      operationId: addToFavorites
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Добавлено в избранное.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/offer"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"

    delete:
      tags: [offers]
      summary: Удалить из избранного
      operationId: removeFromFavorites
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Удалено из избранного.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/offer"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"

  /comments/{offerId}:
    get:
      tags: [comments]
      summary: Получить комментарии для предложения
      operationId: getCommentsByOffer
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Список комментариев.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/comment"
        "404":
          $ref: "#/components/responses/NotFoundError"

    post:
      tags: [comments]
      summary: Добавить комментарий
      operationId: createComment
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createComment"
      responses:
        "201":
          description: Комментарий создан.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/comment"
        "400":
          $ref: "#/components/responses/ValidationError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/NotFoundError"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Пользователь не авторизован. Требуется токен доступа.
    ValidationError:
      description: Ошибка валидации данных.
    NotFoundError:
      description: Ресурс не найден.
    InternalError:
      description: Внутренняя ошибка сервера.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"

  schemas:
    error:
      type: object
      properties:
        message:
          type: string
          example: Внутренняя ошибка сервера
        code:
          type: integer
          example: 500

    createUser:
      type: object
      required: [name, email, password, type]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 15
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 6
          maxLength: 12
        type:
          type: string
          enum: [regular, pro]

    loginUser:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
        password:
          type: string

    user:
      type: object
      required: [id, name, email, type]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
        avatarUrl:
          type: string
        type:
          type: string
          enum: [regular, pro]

    authToken:
      type: object
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIs..."
        expiresIn:
          type: integer
          example: 3600

    createOffer:
      type: object
      required:
        - title
        - description
        - city
        - previewImage
        - images
        - isPremium
        - type
        - bedrooms
        - maxAdults
        - price
        - goods
        - location
      properties:
        title:
          type: string
          minLength: 10
          maxLength: 100
        description:
          type: string
          minLength: 20
          maxLength: 1024
        city:
          type: string
          enum: [Paris, Cologne, Brussels, Amsterdam, Hamburg, Dusseldorf]
        previewImage:
          type: string
        images:
          type: array
          minItems: 6
          maxItems: 6
          items:
            type: string
        isPremium:
          type: boolean
        type:
          type: string
          enum: [apartment, house, room, hotel]
        bedrooms:
          type: integer
          minimum: 1
          maximum: 8
        maxAdults:
          type: integer
          minimum: 1
          maximum: 10
        price:
          type: integer
          minimum: 100
          maximum: 100000
        goods:
          type: array
          items:
            type: string
        location:
          type: object
          required: [latitude, longitude]
          properties:
            latitude:
              type: number
              format: float
            longitude:
              type: number
              format: float

    updateOffer:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        city:
          type: string
          enum: [Paris, Cologne, Brussels, Amsterdam, Hamburg, Dusseldorf]
        previewImage:
          type: string
        images:
          type: array
          minItems: 6
          maxItems: 6
          items:
            type: string
        isPremium:
          type: boolean
        type:
          type: string
          enum: [apartment, house, room, hotel]
        bedrooms:
          type: integer
        maxAdults:
          type: integer
        price:
          type: integer
        goods:
          type: array
          items:
            type: string
        location:
          type: object
          properties:
            latitude:
              type: number
              format: float
            longitude:
              type: number
              format: float

    offerListItem:
      type: object
      required: [id, title, type, price, city, previewImage]
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        type:
          type: string
          enum: [apartment, house, room, hotel]
        price:
          type: integer
        city:
          type: string
        previewImage:
          type: string
        isFavorite:
          type: boolean
        isPremium:
          type: boolean
        rating:
          type: number
          minimum: 1
          maximum: 5
        commentsCount:
          type: integer
        postDate:
          type: string
          format: date-time

    offer:
      type: object
      required:
        - id
        - title
        - description
        - city
        - price
        - host
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        postDate:
          type: string
          format: date-time
        city:
          type: string
        previewImage:
          type: string
        images:
          type: array
          items:
            type: string
        isPremium:
          type: boolean
        isFavorite:
          type: boolean
        rating:
          type: number
          minimum: 1
          maximum: 5
        type:
          type: string
          enum: [apartment, house, room, hotel]
        bedrooms:
          type: integer
        maxAdults:
          type: integer
        price:
          type: integer
        goods:
          type: array
          items:
            type: string
        host:
          $ref: "#/components/schemas/user"
        commentsCount:
          type: integer
        location:
          type: object
          required: [latitude, longitude]
          properties:
            latitude:
              type: number
              format: float
            longitude:
              type: number
              format: float

    createComment:
      type: object
      required: [text, rating]
      properties:
        text:
          type: string
          minLength: 5
          maxLength: 1024
        rating:
          type: integer
          minimum: 1
          maximum: 5

    comment:
      type: object
      required: [id, text, rating, author]
      properties:
        id:
          type: string
          format: uuid
        text:
          type: string
        postDate:
          type: string
          format: date-time
        rating:
          type: integer
          minimum: 1
          maximum: 5
        author:
          $ref: "#/components/schemas/user"
